Float -> Int for Top-k
Top-k should be a positive integer: 

```
Error: top_k has to be a strictly positive integer, but is 3.0
```

which cannot be fixed because it's a float in web.py.